apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  labels:
    {{- include "optimism-id-issuer.staticLabel" . | nindent 4 }}
    {{- include "optimism-id-issuer.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.staticIpName }}
    networking.gke.io/managed-certificates: managed-cert
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/v1beta.FrontendConfig: "http-to-https"
spec:
  rules:
  - host: {{ .Values.apphost }}
    http:
      paths:
        {{- range .Values.ingress.apphost.paths }}
        - path: {{ .path }}
          pathType: Prefix
          backend:
            service:
              name: {{ .serviceName }}
              port:
                number: {{ .servicePort }}
        {{- end }}

  - host: {{ .Values.uihost }}
    http:
      paths:
        {{- range .Values.ingress.uihost.paths }}
        - path: {{ .path }}
          pathType: Prefix
          backend:
            service:
              name: {{ .serviceName }}
              port:
                number: {{ .servicePort }}
        {{- end }}

  - host: {{ .Values.apihost }}
    http:
      paths:
        {{- range .Values.ingress.apihost.paths }}
        - path: {{ .path }}
          pathType: Prefix
          backend:
            service:
              name: {{ .serviceName }}
              port:
                number: {{ .servicePort }}
        {{- end }}
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert
spec:
  domains:
    - {{ .Values.apphost }}
    - {{ .Values.uihost }}
    - {{ .Values.apihost }}