apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgresIssuerNode.pvc.postgres }}
  labels:
  {{- include "optimism-id-issuer.labels" . | nindent 4 }} 
spec:
  storageClassName: {{ .Values.postgresIssuerNode.pvc.storageClass  }}
  accessModes:
  - {{ .Values.postgresIssuerNode.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.postgresIssuerNode.pvc.storageRequest  }}